(part "CI1104M1VR0-NH"
    (packageRef "CI1104M1VR0NH")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "MP1" (symbPinId 5) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 6) (portName "MP2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "CivLux")
    (property "Manufacturer_Part_Number" "CI1104M1VR0-NH")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Connector Header Surface Mount 4 position 0.039" (1.00mm)")
    (property "Datasheet_Link" "https://www.cvilux.com/uploads/drawings/100/224/CI1152S.pdf")
    (property "symbolName1" "CI1104M1VR0-NH")
)
